apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticationservice                # CHANGE THIS TO YOUR SERVICE NAME
  labels:
    app: authenticationservice               # CHANGE THIS TO YOUR SERVICE NAME
spec:
  selector:
    matchLabels:
      app: authenticationservice             # CHANGE THIS TO YOUR SERVICE NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: authenticationservice           # CHANGE THIS TO YOUR SERVICE NAME
    spec:
      containers:
      - name: authenticationservice          # CHANGE THIS TO YOUR SERVICE NAME
        image: dm885/authenticationservice          # CHANGE THIS TO YOUR DOCKER IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: mysqlHost 
          value: "mysql.default.svc.cluster.local"
        - name: mysqlUser
          value: "root"
        - name: mysqlPass
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-root-password
        - name: mysqlDb
          value: "auth"
        - name: rabbitHost
          value: "rabbitmq-0.rabbitmq.rabbits.svc.cluster.local"
        - name: rabbitPort
          value: "5672"
        - name: rabbitUser
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBIT_USERNAME
        - name: rabbitPass
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: RABBIT_PASSWORD
        - name: userUsername
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: user-username
        - name: userPassword
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: user-password
        - name: adminUsername
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: admin-username
        - name: adminPassword
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: admin-password
---
apiVersion: v1
kind: Service
metadata:
  name: authenticationservice              # CHANGE THIS TO YOUR SERVICE NAME
  labels:
    app: authenticationservice             # CHANGE THIS TO YOUR SERVICE NAME
spec:
  type: ClusterIP
  selector:
    app: authenticationservice             # CHANGE THIS TO YOUR SERVICE NAME
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
